init:
  image: svenahlfeld/rediscluster:v3.0
  links:
  - redis
  environment:
   REDIS_NODE_PORT: ${redis_port}
   REDIS_SCALE: ${redis_scale}
   REDIS_REPLICATION: ${rep_factor}
  labels:
   io.rancher.container.start_once: true
  command: /redis/bootstrap.sh init

redis:
  labels:
   io.rancher.container.hostname_override: container_name
  environment:
   REDIS_NODE_PORT: ${redis_port}
   REDIS_SCALE: ${redis_scale}
   REDIS_REPLICATION: ${rep_factor}
  image: svenahlfeld/rediscluster:v3.0