jobmanager:
   environment:
    FLINK_TM_RAM: ${flink_taskmanager_memory}
    FLINK_JM_RAM: ${flink_jobmanager_memory}
    FLINK_TM_SLOTS: ${flink_taskmanager_slots}
   image: svenahlfeld/flinkcluster:1.0.3
   labels:
    io.rancher.container.hostname_override: container_name
   ports:
   - ${jobmanager_port}:8081
   expose:
   - 6123
   - 22
   external_links:
   - ${zk_link}
   - ${kafka_link}
   - ${redis_link}
   - ${es_link}
   links:
   - taskmanager
   command: /usr/local/flink-1.0.3/bin/start-flink-cluster.sh master

taskmanager:
   environment:
    FLINK_TM_RAM: ${flink_taskmanager_memory}
    FLINK_JM_RAM: ${flink_jobmanager_memory}
    FLINK_TM_SLOTS: ${flink_taskmanager_slots}
   labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity: container_label_soft_ne:io.rancher.stack_service.name=$${stack_name}/taskmanager
   image: svenahlfeld/flinkcluster:1.0.3
   expose:
   - 6121
   - 6122
   external_links:
   - ${zk_link}
   - ${kafka_link}
   - ${redis_link}
   - ${es_link}
